name: Build
on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-linux:
    name: Build for Linux
    strategy:
      fail-fast: false
      matrix:
        os:
          - debian-latest
          - debian-sid
          - fedora-latest
          - fedora-rawhide
          - rhel-7
          - rhel-8
          - rhel-latest
          - ubuntu-20-04
          - ubuntu-latest
    runs-on: ubuntu-latest
    container: ghcr.io/stboyden/codectrl-pkg/${{ matrix.os }}:latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: STBoyden/codectrl-protobuf-specifications
          path: crates/protobuf-bindings/protos

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: Fetch cache if already exists
        continue-on-error: true
        uses: actions/cache@v3
        id: has-cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ matrix.os }}-${{ hashFiles('**/Cargo.lock') }}

      - if: steps.has-cache.outputs.cache-hit != 'true' && (contains(matrix.os, 'ubuntu') || contains(matrix.os, 'debian'))
        name: Install cargo-deb
        continue-on-error: true
        run: cargo install cargo-deb

      - if: steps.has-cache.outputs.cache-hit != 'true' && (contains(matrix.os, 'ubuntu') || contains(matrix.os, 'debian'))
        name: Build and package CodeCTRL for DEB-based systems
        shell: bash
        run: |
          cargo deb

      - if: steps.has-cache.outputs.cache-hit != 'true' && (contains(matrix.os, 'fedora') || contains(matrix.os, 'rhel'))
        name: Install cargo-generate-rpm
        continue-on-error: true
        run: cargo install cargo-generate-rpm

      - if: steps.has-cache.outputs.cache-hit != 'true' && (contains(matrix.os, 'fedora') || contains(matrix.os, 'rhel'))
        name: Build and package CodeCTRL for RPM-based systems
        shell: bash
        run: |
          cargo build --release
          strip -s target/release/codectrl
          cargo generate-rpm

      - if: steps.has-cache.outputs.cache-hit != 'true'
        name: Rename output
        run: ./find-and-rename-pkg.sh

      - if: contains(matrix.os, 'ubuntu') || contains(matrix.os, 'debian')
        name: Upload .deb artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }} package
          path: target/debian/*.deb

      - if: contains(matrix.os, 'fedora') || contains(matrix.os, 'rhel')
        name: Upload .rpm artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }} package
          path: target/generate-rpm/*.rpm

  build-macos:
    name: Build for MacOS
    strategy:
      fail-fast: false
      matrix:
        version: [13, 12, 11]
        arch: [x86_64, aarch64]
    runs-on: macos-${{ matrix.version }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: STBoyden/codectrl-protobuf-specifications
          path: crates/protobuf-bindings/protos

      - uses: actions-rs/toolchain@v1
        with:
          target: ${{ matrix.arch }}-apple-darwin
          toolchain: nightly

      - name: Fetch cache if already exists
        continue-on-error: true
        uses: actions/cache@v3
        id: has-cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: macos-${{ matrix.version }}-${{ matrix.arch }}-${{ hashFiles('**/Cargo.lock') }}

      - if: steps.has-cache.outputs.cache-hit != 'true'
        name: Install cargo-bundle
        continue-on-error: true
        run: cargo install cargo-bundle

      - if: steps.has-cache.outputs.cache-hit != 'true'
        name: Build and package for MacOS ${{ matrix.version }}
        run: cargo bundle --release --target ${{ matrix.arch }}-apple-darwin

      - name: Upload .app artifact
        uses: actions/upload-artifact@v3
        with:
          name: MacOS ${{ matrix.version }} ${{ matrix.arch }} package
          path: target/release/bundle/osx/*.app

  build-windows:
    name: Build for Windows
    strategy:
      fail-fast: false
      matrix:
        version: [2022, 2019]
    runs-on: windows-${{ matrix.version }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: STBoyden/codectrl-protobuf-specifications
          path: crates/protobuf-bindings/protos

      - name: Fetch cache if already exists
        continue-on-error: true
        uses: actions/cache@v3
        id: has-cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: windows-${{ matrix.version }}-${{ hashFiles('**/Cargo.lock') }}

      - if: steps.has-cache.outputs.cache-hit != 'true'
        name: Install cargo-wix
        continue-on-error: true
        run: cargo install cargo-wix

      - if: steps.has-cache.outputs.cache-hit != 'true'
        name: Build CodeCTRL
        run: cargo build --release

      - if: steps.has-cache.outputs.cache-hit != 'true'
        name: Generate MSI
        run: cargo wix --nocapture --no-build -p codectrl

      - name: Upload .msi artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows ${{ matrix.version }} MSI
          path: target/wix/*.msi

      - name: Cache binary
        uses: actions/cache@v3
        id: cache-binary
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: windows-${{ matrix.version }}-${{ hashFiles('**/Cargo.lock') }}

  all-in-one:
    name: Combine packages
    runs-on: ubuntu-22.04
    needs:
      - build-linux
      - build-macos
      - build-windows
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2

      - name: Upload Zip
        uses: actions/upload-artifact@v3
        with:
          name: All-in-One CodeCTRL Packages
          path: .

      - name: Generate step summary
        run: |
          echo -e "Download links:" >> $GITHUB_STEP_SUMMARY
          echo -e "- Windows 10/11 - [built on latest Windows server](https://nightly.link/STBoyden/codectrl/workflows/build-and-package/main/Windows%20latest%20MSI.zip) or [built on Windows server 2019](https://nightly.link/STBoyden/codectrl/workflows/build-and-package/main/Windows%202019%20MSI.zip)" >> $GITHUB_STEP_SUMMARY
          echo -e "- Linux" >> $GITHUB_STEP_SUMMARY
          echo -e "\t- Ubuntu - [latest LTS (22.04)](https://nightly.link/STBoyden/codectrl/workflows/build-and-package/main/ubuntu-latest%20package.zip) or [20.04](https://nightly.link/STBoyden/codectrl/workflows/build-and-package/main/ubuntu-20-04%20package.zip)" >> $GITHUB_STEP_SUMMARY
          echo -e "\t- Debian - [12 (Bookworm)](https://nightly.link/STBoyden/codectrl/workflows/build-and-package/main/debian-latest%20package.zip) or [Sid](https://nightly.link/STBoyden/codectrl/workflows/build-and-package/main/debian-sid%20package.zip)" >> $GITHUB_STEP_SUMMARY
          echo -e "\t- Fedora - [38](https://nightly.link/STBoyden/codectrl/workflows/build-and-package/main/fedora-latest%20package.zip) or [Rawhide](https://nightly.link/STBoyden/codectrl/workflows/build-and-package/main/fedora-rawhide%20package.zip)" >> $GITHUB_STEP_SUMMARY
          echo -e "\t- RHEL - [7](https://nightly.link/STBoyden/codectrl/workflows/build-and-package/main/rhel-7%20package.zip), [8](https://nightly.link/STBoyden/codectrl/workflows/build-and-package/main/rhel-8%20package.zip), or [9](https://nightly.link/STBoyden/codectrl/workflows/build-and-package/main/rhel-latest%20package.zip)" >> $GITHUB_STEP_SUMMARY
          echo -e "" >> $GITHUB_STEP_SUMMARY
          echo -e "A combined zip containing all the above files can be downloaded [here](https://nightly.link/STBoyden/codectrl/workflows/build-and-package/main/All-in-One%20CodeCTRL%20Packages.zip)"
