name: Auto-update Build Containers
on:
  push:
    branches: [main, update-containers/*]
  schedule:
    - cron: "0 */2 * * */1"

jobs:
  build-containers:
    if: github.repository_owner == 'STBoyden'
    strategy:
      matrix:
        os:
          - debian-latest
          - debian-sid
          - fedora-latest
          - fedora-rawhide
          - rhel-7
          - rhel-8
          - rhel-latest
          - ubuntu-20-04
          - ubuntu-latest
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3

      - uses: satackey/action-docker-layer-caching@v0.0.11
        with:
          key: ${{ matrix.os }}-{hash}
        continue-on-error: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Build and push for ${{ matrix.os }}
        uses: docker/build-push-action@v3
        with:
          context: ./.github/containers/${{ matrix.os }}
          platforms: linux/amd64
          push: true
          driver-opts: |
            network=host
          tags: |
            ghcr.io/stboyden/codectrl-pkg/${{ matrix.os }}:latest
            ghcr.io/stboyden/codectrl-pkg/${{ matrix.os }}:${{ github.sha }}
